# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Metadata-ByInode
version:      1.16
version_from: lib/Metadata/ByInode.pm
installdirs:  site
requires:
    Carp:                          1
    DBD::SQLite:                   1
    DBI:                           1
    File::Find::Rule:              0
    Smart::Comments:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
